class Ticker:
    SYMBOL = "SYMBOL"
    NAME_OF_COMPANY = "NAME OF COMPANY"
    SERIES = "SERIES"
    DATE_OF_LISTING = "DATE OF LISTING"
    PAID_UP_VALUE = "PAID UP VALUE"
    MARKET_LOT = "MARKET LOT"
    ISIN_NUMBER = "ISIN NUMBER"
    FACE_VALUE = "FACE VALUE"

class BhavData:
    SYMBOL = "SYMBOL"
    SERIES = "SERIES"
    DATE1 = "DATE1"
    PREV_CLOSE = "PREV_CLOSE"
    OPEN_PRICE = "OPEN_PRICE"
    HIGH_PRICE = "HIGH_PRICE"
    LOW_PRICE = "LOW_PRICE"
    LAST_PRICE = "LAST_PRICE"
    CLOSE_PRICE = "CLOSE_PRICE"
    AVG_PRICE = "AVG_PRICE"
    TTL_TRD_QNTY = "TTL_TRD_QNTY"
    TURNOVER_LACS = "TURNOVER_LACS"
    NO_OF_TRADES = "NO_OF_TRADES"
    DELIV_QTY = "DELIV_QTY"
    DELIV_PER = "DELIV_PER"


class ChangeCapture:
    SYMBOL = "SYMBOL"

class DBkey:
    SYMBOL_key = "symbol"

class AUDITCOLS:
    LAST_UPDATED = "last_updated"

    
